### ISSUE TITLE
Need better dupe logic

### ISSUE THREAD

**Issue by Chankster** [skullydazed/kalerator#2]
When using the [ANSI 104 layout from the KLE templates](http://kalerator.clueboard.co/view/gists/41715e028c3139825e6f?eagle_version=paid) the \* on the numpad gets dupe'd against the already dupe'd numpad 8.

[http://i.imgur.com/mNfv7Td.png](http://i.imgur.com/mNfv7Td.png)

**Comment by skullydazed** [comment]
This is fixed in c5395 and will be rolled out with the next release.
